RUN apt update \
    && apt install -y \
        bash unzip wget python python-pip software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 && \
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list.d/ansible.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
      ansible

RUN pip install boto boto3 botocore

RUN npm install yarn -g
